import FileManagerProtocol
import Foundation
import Subprocess
#if canImport(System)
    import System
#else
    import SystemPackage
#endif

/// Generates a new Swift Package configured as a linter project.
public struct Scaffold {
    private let fileManager: any FileManagerProtocol

    /// Creates a scaffold backed by the given file manager.
    public init(fileManager: some FileManagerProtocol = FileManager.default) {
        self.fileManager = fileManager
    }

    /// Generates a linter package at `path` with the given `name`.
    public func generate(at path: String, name: String) async throws {
        let resolvedPath = URL(filePath: path).standardized.path(percentEncoded: false)

        if !fileManager.fileExists(atPath: resolvedPath) {
            try fileManager.createDirectory(atPath: resolvedPath, withIntermediateDirectories: true)
        }

        try await initPackage(at: resolvedPath, name: name)
        try await addDependencies(at: resolvedPath)
        try await addTargets(at: resolvedPath)
        try await addTargetDependencies(at: resolvedPath)
        removeAutoGeneratedEntryPoint(at: resolvedPath)
        try writeSourceFiles(at: resolvedPath)
        try writeFile(content: Constants.ymlTemplate, atPath: "\(resolvedPath)/\(Constants.configFileName)")
    }

    // MARK: - Package Setup

    private func initPackage(at path: String, name: String) async throws {
        try await runSwift(packagePath: path, arguments: ["init", "--type", "empty", "--name", name])

        let packageSwiftPath = "\(path)/Package.swift"
        let packageContent = try String(contentsOfFile: packageSwiftPath, encoding: .utf8)
        let patched = packageContent.replacingOccurrences(
            of: "name: \"\(name)\",",
            with: "name: \"\(name)\",\n    platforms: [.macOS(.v15)],",
        )
        try writeFile(content: patched, atPath: packageSwiftPath)
    }

    private func addDependencies(at path: String) async throws {
        try await runSwift(packagePath: path, arguments: [
            "add-dependency",
            Constants.swiftASTLintURL,
            "--from", Constants.swiftASTLintMinVersion,
        ])
        try await runSwift(packagePath: path, arguments: [
            "add-dependency",
            Constants.swiftSyntaxURL,
            "--from", Constants.swiftSyntaxMinVersion, "--to", Constants.swiftSyntaxMaxVersion,
        ])
    }

    private func addTargets(at path: String) async throws {
        try await runSwift(packagePath: path, arguments: [
            "add-target", Constants.rulesTarget, "--type", "library",
        ])
        try await runSwift(packagePath: path, arguments: [
            "add-target", Constants.executableTarget,
            "--type", "executable", "--dependencies", Constants.rulesTarget,
        ])
        try await runSwift(packagePath: path, arguments: [
            "add-target", Constants.testTarget,
            "--type", "test", "--dependencies", Constants.rulesTarget,
        ])
    }

    private func addTargetDependencies(at path: String) async throws {
        try await runSwift(packagePath: path, arguments: [
            "add-target-dependency",
            Constants.swiftASTLintProduct, Constants.rulesTarget,
            "--package", Constants.swiftASTLintPackage,
        ])
        try await runSwift(packagePath: path, arguments: [
            "add-target-dependency",
            Constants.swiftSyntaxProduct, Constants.rulesTarget,
            "--package", Constants.swiftSyntaxPackage,
        ])
        try await runSwift(packagePath: path, arguments: [
            "add-target-dependency",
            Constants.testSupportProduct, Constants.testTarget,
            "--package", Constants.swiftASTLintPackage,
        ])
    }

    private func removeAutoGeneratedEntryPoint(at path: String) {
        let autoGenerated = "\(path)/Sources/\(Constants.executableTarget)/\(Constants.executableTarget).swift"
        if fileManager.fileExists(atPath: autoGenerated) {
            try? fileManager.removeItem(atPath: autoGenerated)
        }
    }

    // MARK: - Private

    private func runSwift(packagePath: String, arguments: [String]) async throws {
        let fullArguments = ["package", "--package-path", packagePath] + arguments
        let result = try await run(
            .name("swift"),
            arguments: Arguments(fullArguments),
            workingDirectory: FilePath(packagePath),
            output: .string(limit: 1024 * 1024),
            error: .string(limit: 1024 * 1024),
        )

        guard result.terminationStatus.isSuccess else {
            let errorOutput = result.standardError ?? ""
            throw ScaffoldError.commandFailed(
                command: "swift \(fullArguments.joined(separator: " "))",
                output: errorOutput,
            )
        }
    }

    private func writeSourceFiles(at path: String) throws {
        let dirs = [
            "\(path)/Sources/\(Constants.rulesTarget)",
            "\(path)/Sources/\(Constants.executableTarget)",
            "\(path)/Tests/\(Constants.testTarget)",
        ]
        for dir in dirs {
            try fileManager.createDirectory(atPath: dir, withIntermediateDirectories: true)
        }

        let files: [(String, String)] = [
            ("Sources/\(Constants.executableTarget)/main.swift", Constants.mainSwift),
            ("Sources/\(Constants.rulesTarget)/Rules.swift", Constants.rulesSwift),
            ("Tests/\(Constants.testTarget)/RulesTests.swift", Constants.rulesTestsSwift),
        ]
        for (subpath, content) in files {
            try writeFile(content: content, atPath: "\(path)/\(subpath)")
        }
    }

    private func writeFile(content: String, atPath path: String) throws {
        guard let data = content.data(using: .utf8) else {
            throw ScaffoldError.commandFailed(command: "write", output: "Failed to encode content to UTF-8")
        }
        _ = fileManager.createFile(atPath: path, contents: data)
    }
}

public enum ScaffoldError: Error, CustomStringConvertible {
    case commandFailed(command: String, output: String)

    public var description: String {
        switch self {
        case let .commandFailed(command, output):
            "\(command) failed: \(output)"
        }
    }
}
